### ISSUE TITLE
Make it compatible with NHibernate 3.3 for Orchard 1.6

### ISSUE THREAD

**Issue by agriffard** [Q42/Orchard-DbTranslations#27]
In Orchard 1.6, NHibernate will be updated to 3.3.
The current 1.x branch contains these changes.
It seems that there is some errors using the Translations module.

**Comment by dseferlis** [comment]
Just figured this out. Was simple enough. I removed faulting NH references and just added NH from orchard lib folder. Then fixed the errors in LocalizationService.cs, where the missing method Linq changed to Query. Still then the site came up with the Orchard.Web filelist instead of homepage. Examining the orchard logs there was the error:
Q42.DbTranslations.Models.LocalizableStringRecord: method set_Translations should be 'public/protected virtual' or 'protected internal virtual'
So in LocalizableStringRecord changed the private set; to protected set;.
Works fine now.

**Comment by agriffard** [comment]
I also did it (I should have said it in the description of the issue) but then, in /Admin/Q42.DbTranslations, There is another error :
 Method 'get_IsReadOnlyInitialized' in type 'NHibernate.Linq.Util.DetachedCriteriaAdapter' from assembly 'NHibernate.Linq, Version=1.1.0.1001, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by dseferlis** [comment]
I can't see such an error. It works fine for me. Did you build solution?

**Comment by agriffard** [comment]
I included the project and redid the references to be able to compile but I still have the error on each tab of /admin/Q42.DbTranslations.
I will ask why the folders linqnhibernate and fluentnhibernate disappeared in Lib

**Comment by dseferlis** [comment]
I think Linq exist in NHibernate.dll. Fluent.IO and Fluent.Zip exist in modules bin folder after installation

**Comment by lukasvan3l** [comment]
Just came back from vacation, will have a look soon!
My projects are still on orchard 1.4, will update to 1.5.1 coming week(s)

**Comment by agriffard** [comment]
Thanks, Can you test with 1.x also for the upcoming 1.6 version ?

**Comment by lukasvan3l** [comment]
Unfortunately it's impossible to get the code working for 1.4 and 1.6 simultaneously.
For the moment I created a 1.6 branch that you can use: https://github.com/Q42/Orchard-DbTranslations/tree/orchard1.6

When 1.6 gets out, I'll change the trunk
