### ISSUE TITLE
not working in 1.7

### ISSUE THREAD

**Issue by santo2** [Q42/Orchard-DbTranslations#33]
Hi all, the Q42 DB Translations module is not working for version 1.7. is this module still going to be kept alive?

**Comment by lukasvan3l** [comment]
I'm afraid I don't have the time to continue work on this module. But it's opensource so you can fork it if needed!

**Comment by pilgylis** [comment]
In case anyone cares, I modified it to work with 1.7: https://github.com/pilgylis/Orchard-DbTranslations

Other changes include:

Work with Orchard 1.7
- Import -> Generate From Source will exclude the _Backup folder, which was used by Orchard to store old versions of modules (just ignore if the name exists in the path, so may work with Themes, not verified yet)
- Import -> Generate from source: added options to generate from a specific module or theme
- More

Will be happy if this is merged with the original line, since I'm too lazy to maintain it :P

**Comment by lukasvan3l** [comment]
Please send a pull request, I'll be happy to merge!

**Comment by pilgylis** [comment]
Pull request sent!

**Comment by lukasvan3l** [comment]
Pull request merged!

I didn't check the solution myself
